# Pimcore Studio API. Studio is a hard requirement of this bundle since 2026.
cors_web_care_studio:
    resource: "@CORSWebCareBundle/Controller/Studio"
    type: attribute
    prefix: '%pimcore_studio_backend.url_prefix%/bundle/web-care'
    options:
        expose: true
